name: Ejecutar notebook diario

on:
  schedule:
    - cron: '0 22 * * *'  # Todos los días a las 5 AM Colombia (UTC-5)
  workflow_dispatch:       # Permite ejecución manual también

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: pip install papermill

      - name: Ejecutar notebook
        run: papermill test.ipynb output.ipynb
